### ISSUE TITLE
Get fps

### ISSUE THREAD

**Issue by stemcoding** [alfg/ffprobe-wasm#10]
I would love to be able to use this to upload a file into the browser and have it return the frame rate of the clip. When I use ffprobe on my local machine the frame rate is easy to find. When I use the web version of ffprobe I can't see this info. I guess this is a feature request.

**Comment by alfg** [comment]
Hey @stemcoding, I'll check into this soon.

**Comment by minikN** [comment]
Well, I guess you have all that you need:
- `duration` in μS
- `frames`

So you can simply calculate the fps with `frames / (duration / 1000000)` ...?

**Comment by maggievu-pdftron** [comment]
Hey @stemcoding, the changes are in [this commit](https://github.com/PDFTron/ffprobe-wasm/commit/f32f277baa972cb7244f47163f059e8dce8cc24e). Hope this helps!

> I would love to be able to use this to upload a file into the browser and have it return the frame rate of the clip. When I use ffprobe on my local machine the frame rate is easy to find. When I use the web version of ffprobe I can't see this info. I guess this is a feature request.

**Comment by stemcoding** [comment]
This is great! I can't wait to use the live version on the web!

**Comment by alfg** [comment]
Hey, sorry for the late response. Thanks for the changes @maggievu-pdftron. Is it possible to submit these in a PR and I can merge them here as well?

**Comment by maggievu-pdftron** [comment]
@alfg You're welcome! [PR](https://github.com/alfg/ffprobe-wasm/pull/12) created

**Comment by alfg** [comment]
Thanks @maggievu-pdftron for the PR! I'll review, merge and deploy this later tonight.

**Comment by alfg** [comment]
Fixed via #12 and deployed to: https://ffprobe-wasm.netlify.app/

Thanks again for the feature, @maggievu-pdftron!
