### ISSUE TITLE
MP3 support

### ISSUE THREAD

**Issue by jhurliman** [alfg/ffprobe-wasm#19]
Attempting to use this on an MP3 file results in the following being printed to the console and an exception is thrown.

```
ERROR: Invalid data found when processing input
RuntimeError: table index is out of bounds
    at wasm://wasm/0087a9be:wasm-function[1057]:0x8c3c3
    at wasm://wasm/0087a9be:wasm-function[2251]:0x138068
    at wasm://wasm/0087a9be:wasm-function[2216]:0x1356d0
    at get_file_info (eval at new_ (.../node_modules/ffprobe-wasm/ffprobe-wasm.js:5577:23), <anonymous>:8:10)
    at getFileInfo (file://.../node_modules/ffprobe-wasm/worker.mjs:56:29)
    at async MessagePort.onmessage (file://.../node_modules/ffprobe-wasm/worker.mjs:9:34)
```

**Comment by alfg** [comment]
Hi @jhurliman, can you attach an mp3 file that I can use for reference. Thanks!

**Comment by jhurliman** [comment]
[preludeincmajor-30s.mp3.zip](https://github.com/alfg/ffprobe-wasm/files/10369906/preludeincmajor-30s.mp3.zip)

**Comment by alfg** [comment]
Thanks! I've updated and deployed the latest enabling MP3 support. 
https://ffprobe-wasm.netlify.app/
