### ISSUE TITLE
Browser does not support SharedArrayBuffer

### ISSUE THREAD

**Issue by bichaorui** [alfg/ffprobe-wasm#20]
HI 
I found that browsers don't currently support SharedArrayBuffer
It can be found under this [URL](https://emscripten.org/docs/porting/pthreads.html) that the pthreads attribute is the key factor, but it cannot be resolved after I deal with it.
Do you have any suggestions?
grateful

**Comment by alfg** [comment]
Hey @bichaorui, which browser are you using? Most should have support and I have the required coop/coep headers enabled.

https://caniuse.com/sharedarraybuffer
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer
