### ISSUE TITLE
Main thread blocking while fetching the frames

### ISSUE THREAD

**Issue by Banou26** [alfg/ffprobe-wasm#6]
When trying to fetch the frames, the main thread locks up, this happens for any file format and can be blocking for a few seconds depending on the frames.

**Comment by alfg** [comment]
Yeah, fetching the frames can be expensive in the browser. I can check into emscripten's asyncify or pthread proxy. I'll look into this soon.

**Comment by alfg** [comment]
I moved the Wasm module calls to a Web Worker so it doesn't block the browser main thread. File loading is much faster now too using Emscripten's workerfs.

https://alfg.github.io/ffprobe-wasm/ is updated with latest build.

#7
